### ISSUE TITLE
[Help] hide root from this regional ID app

### ISSUE THREAD

**Issue by 54m4d** [MhmRdd/NoHello#40]
[This ID app](https://play.google.com/store/apps/details?id=no.vipps.bankid) was working perfectly fine last week until it got updated a couple of days ago, and now it closes as soon as opening it without giving any errors, but I'm sure it's detecting root since it's working just fine on an unrooted device which I don't use.

Galaxy S21 A15

Magisk 29001 (Canary)

I tried both, NoHello and Shamiko (one at a time)

I tried Magisk Alpha with the both modules above without any luck

I added the app to HMAL, this didn't help.

Any suggestion would be appreciated, Thanks.

<details>
<summary>Screenshots</summary>
<img src=https://github.com/user-attachments/assets/fe90fb30-c42a-48fb-926c-229780fe841d>
<img src=https://github.com/user-attachments/assets/8f237b03-d7a6-44da-b3b3-e06eba85d897>
<img src=https://github.com/user-attachments/assets/f816106d-45e2-46b4-a751-9b655dd3aff9>
<img src=https://github.com/user-attachments/assets/1ebeeb71-0048-4340-8c9b-d34ca2419a2a>
<img src=https://github.com/user-attachments/assets/2d083b1b-9917-464b-a562-ebb3936855d4>
<img src=https://github.com/user-attachments/assets/85c09a3d-1b78-4fbc-a9b2-bd127c81b5f9>
</details>

**Comment by MhmRdd** [comment]
Try Vold Isolation + HMA + LSP (JingMatrix or Lrena)
ZN 1.2.9 + Shamiko + NoHello

this should work now

**Comment by 54m4d** [comment]
Have you tried this?

I turned on Vold Isolation in HMA and tried again, but the app is still crashing upon opening

When I turn on Shamiko, NoHello gives a warning that there are conflicts.

<details>
<summary>This is how it looks</summary>
<img src=https://github.com/user-attachments/assets/1b617c99-66e3-4d29-9649-13192676af88>
<img src=https://github.com/user-attachments/assets/ae3382b5-6908-4161-a1b3-6fb70ede7b42>
<img src=https://github.com/user-attachments/assets/56154bb4-54bc-48df-81d6-73ab6154fa2d>
</details>

**Comment by MhmRdd** [comment]
Yes it's all okay, it makes Shamiko unmount instead of NoHello, sometimes Shamiko might be better at unmounting, and sometimes NoHello can pass more Zygisk detections than Shamiko.
Using both will mix their effects.

**Comment by MhmRdd** [comment]
Did you put it on denylist?
Can you check if you added all the apps that are suspicious to HMA blacklist and selected the right all to hide for?
If yes, please try other detectors such as NT, Holmes, etc.... and let me know back.

Sometimes the app might be checking KeyAttestation, it's worth trying to add it in `target.txt` in `/data/adb/tricky_store` if you have it installed.

**Comment by 54m4d** [comment]
<details>
<summary>This is how it looks</summary>
<img src=https://github.com/user-attachments/assets/6f4a7a85-ef1d-48ec-8775-e2787195fe90>
<img src=https://github.com/user-attachments/assets/737cde6e-936b-4daa-8e09-8e74c1066063>
<img src=https://github.com/user-attachments/assets/739579e4-029d-4255-98e2-f2c39794e3d4>

</details>

**Comment by 54m4d** [comment]
Yes, but it doesn't work still

**Comment by MhmRdd** [comment]
Can you check if NT & Holmes say Normal?

**Comment by 54m4d** [comment]
No, there are still detections

**Comment by MhmRdd** [comment]
Can you show them at least so i can figure out what's missing?

**Comment by MhmRdd** [comment]
This seems to be a kernel issue, maybe try Magisk Alpha with the original stock kernel?

**Comment by Lastpickle** [comment]
![Image](https://github.com/user-attachments/assets/1edb4
6d9-ebfa-4bc2-a1b0-0150709c0a66)
Works

**Comment by 54m4d** [comment]
I will try this immediately

**Comment by Lastpickle** [comment]
Nice to know that your  problem is fixed.
I known this as bhim UPI (Indian payment app)requires this process too
